models/formSubmissions.model.js

Updated formSubmissions.model.js

---

models/user.model.js

Issue: 6
Added the user schema setting name and email as required fields and verified by default as false following mongoose schema structure
-
-
-

User model added by SanyamAgrawal07

---

package-lock.json
package.json
utils/password.js

Issue: 10
I just install bcryptjs module . Taking password from user as a req.body and hash it.

Added has_password funtion in utils folder

---

models/form.model.js

Issue: 8
Created schema in `models/form.model.js`
- `submissions` field is now an array of ObjectIds with ref to `formSubmission`
-

Added form model (updated)

---

controllers/auth.controller.js
routes/auth.routes.js
utils/password.js

Issue: 21
Added code for logging in
- added a controller login at route /login
- changed the password hashing function to use different library as the earlier one was not working as expected

Added Log In Functionality

---

controllers/auth.controller.js
package-lock.json
package.json

Issue: 23
SignUp function added in controllers/auth.controller.js
-
-
-

SignUp functionality added

---

app.js

Cors enabled for all

---

email-templates/verification-Vishesh-Vijay.html

task2 completed

---

models/project.model.js

Issue: 36
Short description of what this resolves:
- added allowRecaptcha field in models
Changes proposed in this pull request and/or Screenshots of changes:
- added allowRecaptcha field in models
-
-

added allowRecaptcha field in models

---

controllers/auth.controller.js

Issue: 41
Added check for Accounts created using Google Auth.

Add check for Account created using Google Auth

---

email-templates/verification-TheDivineAurora.html

Issue: 33
33
mail template
-
-
-

mail template issue _ 33

---

email-templates/verification-Kali-Decoder.html

Issue: 33
Create e email verification template for verify user after login as per figma design color schema .
-
-
-

Create : Verify-Email-Template

---

email-templates/verification-frikinomad.html

Issue: 33
Short description of what this resolves:
- added email verification for frikinomad
Changes proposed in this pull request and/or Screenshots of changes:
- added email verification for frikinomad
-
-

added email verification for frikinomad

---

controllers/auth.controller.js
routes/auth.routes.js

Google OAuth Feature

---

controllers/auth.controller.js

Issue: 47
Added if statements to check the fields and formatted the authGoogle function to remove extra whitespaces in the front. 
-
-
-

Missing fields in req in authcontroller

---

email-templates/verification-GammaMicrowave.html

Issue: 33
added email template

added email template

---

package-lock.json
package.json
utils/mailer.js

sendVerifiactionLink function completed

---

utils/password.js

Expiry in getJwt function

---

controllers/auth.controller.js
controllers/user.controller.js
models/user.model.js

getVerificationLink function added in userController

---

controllers/user.controller.js

updateUser function added in userController.js

---

controllers/user.controller.js

updatePassword function added in user.controller.js

---

controllers/user.controller.js
routes/user.routes.js

Issue: 59
- Adds the verify user email route.
- Takes JWT secret from URL params, marks user as verified if secret is verifiable otherwise sends bad response.

Add verify user email route

---

controllers/user.controller.js

getUser added in user.controller.js

---

controllers/user.controller.js
routes/user.routes.js

Issue: 66
added dashboard in router.user.js

added dashboard get request function

---

controllers/user.controller.js
middlewares/verify.middleware.js
routes/user.routes.js

added routes for user

---

controllers/project.controller.js

createProject function added

---

controllers/project.controller.js

Project dashboard

---

controllers/project.controller.js

Issue: 77
- Adds controller function to update a project

Add update project controller

---

config/db.config.js
middlewares/file.middleware.js
package-lock.json
package.json

GridFS initialization

---

controllers/form.controller.js

createForm function added

---

routes/project.routes.js

Issue: 84
- Adds project routes in `project.routes.js`

Add project routes

---

utils/mailer.js

Collab invitation mail

---

controllers/form.controller.js
controllers/project.controller.js
models/form.model.js
models/formSubmissions.model.js
models/project.model.js

Issue: 102
updated  id field names in models and controllers

updated id field name

---

controllers/form.controller.js

Pagination in form dashboard

---

controllers/project.controller.js

inviteCollaborators function in projectController

---

controllers/form.controller.js
controllers/project.controller.js

project and form limitations

---

controllers/form.controller.js
controllers/project.controller.js
models/form.model.js
models/formSubmissions.model.js
models/project.model.js
utils/generateRandomString.js

Now everytime a project/form is created it would generate a new randomId for them.
This was not happening before because  each time we run a server it would run the schema and generate the default value as a constant string. To avoid this I converted that randomString function into a util function and called it every time we need to make a new Form or Project.

fixed issue of randomString generating only once

---

controllers/project.controller.js

Created controller to update collaborators status
